### ISSUE TITLE
I can't tell if it's doing anything

### ISSUE THREAD

**Issue by GordonsBeard** [NotNite/WebfishingRichPresence#1]
I've installed the mod but I cannot seem to confirm it's doing anything. My discord presence still just says "WEBFISHING" unless there is some way to check it I cannot figure out.

Mods folder:
![image](https://github.com/user-attachments/assets/94f53f94-445b-44ac-bcc0-e62d3da2fb1a)

discord_game_sdk.dll:
![image](https://github.com/user-attachments/assets/7c300ebe-1877-41dd-bcfe-14da36149018)

But my discord just seems to say nothing new:
![image](https://github.com/user-attachments/assets/4d8b3f8e-e201-44c7-a02e-9b191a0d832b)
![image](https://github.com/user-attachments/assets/be9dfbcf-7540-4d7e-bf26-8abc5c4fa37b)

**Comment by RemiFoxin** [comment]
I had this issue. Fixed it by extracting everything into the main game location.

Edit: Should note I also kept the folder version within the Mods.

**Comment by GordonsBeard** [comment]
My issue was that I had the feature disabled in Discord, my apologies!
